### ISSUE TITLE
in order to try pls help where to buy fpga toolkit for machine learning?

### ISSUE THREAD

**Issue by Sandy4321** [darrinwillis/neuralHardware#1]
in order to try pls help where to buy fpga toolkit for machine learning?

**Comment by darrinwillis** [comment]
Here's a link to [Altera's shop]( http://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=163#Category165)
I used the [DE2-115](http://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=165&No=502) for this project.
